export default {
    swiper1: require("./exampleImg/swiper1.jpg"),
    swiper2: require("./exampleImg/swiper2.jpg"),
    swiper3: require("./exampleImg/swiper3.jpg"),
    hotIssue0: require("./exampleImg/issue0.jpg"),
    hotIssue1: require("./exampleImg/issue1.jpg"),
    hotIssue2: require("./exampleImg/issue2.jpg"),
    hotIssue3: require("./exampleImg/issue3.jpg"),
    hotIssue4: require("./exampleImg/issue4.jpg"),
    headImg1: require("./exampleImg/headImg1.jpg"),
    headImg2: require("./exampleImg/headImg2.jpg"),
    headImg3: require("./exampleImg/headImg3.jpg"),
    headImg4: require("./exampleImg/headImg4.jpg"),
    headImg5: require("./exampleImg/headImg5.jpg"),
    headImg6: require("./exampleImg/headImg6.jpg"),
    book1: require("./exampleImg/book1.jpg"),
    book2: require("./exampleImg/book2.jpg"),
    book3: require("./exampleImg/book3.jpg"),
    book4: require("./exampleImg/book4.png"),
    book5: require("./exampleImg/book5.jpg"),
    book6: require("./exampleImg/book6.jpg"),
    film1: require("./exampleImg/film1.png"),
    film2: require("./exampleImg/film2.png"),
    film3: require("./exampleImg/film3.png"),
    film4: require("./exampleImg/film4.png"),
    film5: require("./exampleImg/film5.png"),
}